FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Set environment variables
ENV NODE_ENV=development
ENV VITE_PORT=5500

# Expose the port the app runs on
EXPOSE 5500

# Command to run the app in development mode
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5500"]
