services:
  vtrack:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vtrack-app
    ports:
      - "5500:5500"
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=5500
    networks:
      - vtrack-network

networks:
  vtrack-network:
    name: vtrack-network
    driver: bridge
